### ISSUE TITLE
Could you please give us the data files? so that we can rerun this code.

### ISSUE THREAD

**Issue by IrvingBei** [adamklec/copynet#3]
Thanks for sharing the code. when I try to run this code, I create the datasets follow your description, _Each file should have 2 lines of text. The first is the input sequence, the second is the target output sequence_. But the error notices that lacking the file of **cleaned_first_names.txt** , so  Could you please give us the data files? so that we can rerun this code. thanks again!

**Comment by ghost** [comment]
Hi
The same issue here, could you please give the data files?

**Comment by adamklec** [comment]
Unfortunately I cannot provide any training data files. This model was developed while on proprietary data set that I no longer have access to. 

@IrvingBei you are correct that this does reference a resource file called cleaned_first_names.txt
This was nothing more than a list of common first names that I used to prevent first names from making it into the model's vocab (I wanted to be sure that any names that appeared in the output were coming from the copy mechanism rather than from the vocab).

Omitting first names from the model's vocab is optional and domain specific so rather than upload that file I will remove the relevant lines from the code.
